import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import AuthContextProvider from "@/components/contexts/AuthContextProvider";
import NavContextProvider from "@/components/contexts/NavContext";
import ModalContextProvider from "@/components/contexts/ModalContextProvider";
import FoldersContextProvider from "@/components/contexts/FoldersContent";
import NotesContextProvider from "@/components/contexts/NotesContextProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <NavContextProvider>
            <ModalContextProvider>
              <FoldersContextProvider>
                <NotesContextProvider>
                  {children}
                  <Toaster />
                </NotesContextProvider>
              </FoldersContextProvider>
            </ModalContextProvider>
          </NavContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
